# Generated by Django 4.0.5 on 2022-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_alter_recipeingredients_quantity_alter_recipes_abv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredients',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
