# Generated by Django 4.0.5 on 2022-06-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_alter_recipeingredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
