# Generated by Django 4.0.5 on 2022-06-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0006_alter_recipes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredients',
            name='alpha_acids',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='unit',
            field=models.CharField(default='oz', max_length=3),
        ),
    ]
