# Generated by Django 4.0.5 on 2022-06-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_useringredients_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='useringredients',
            name='unit',
        ),
    ]
