# Generated by Django 4.0.5 on 2022-06-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_remove_recipeingredients_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
