# Generated by Django 4.0.5 on 2022-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0011_alter_useringredients_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredients',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
