# Generated by Django 4.0.5 on 2022-06-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0019_alter_recipeingredients_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='styles',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='useringredients',
            options={'ordering': ['quantity']},
        ),
        migrations.AddField(
            model_name='styles',
            name='image',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
