# Generated by Django 4.0.5 on 2022-06-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0020_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useringredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ingredients', to='app_api.ingredients'),
        ),
    ]
