# Generated by Django 4.0.5 on 2022-06-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0022_alter_recipeingredients_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
