# Generated by Django 4.0.5 on 2022-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0023_alter_ingredients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
